### ISSUE TITLE
Don't change encoding/decoding settings

### ISSUE THREAD

**Issue by eXpl0it3r** [cryptii/cryptii#10]
When swapping between encoders, the encoding/decoding setting will always switch back to encoding, which is really annoying, because once you hit "encoding" again, it will swap the left and right text, which of course then doesn't work.

Alternatively, don't swap texts when switching between encoding and decoding.

**Comment by ffraenz** [comment]
Annoying indeed! The new brick will now keep the encode / decode state of the previous one. Thank's for your feedback!
