### ISSUE TITLE
Ascii85 broken

### ISSUE THREAD

**Issue by bgever** [cryptii/cryptii#12]
Thanks for this great service, love the interface!

Unfortunately I found that I cannot reliably encode random 256-bit key from binary to Ascii85 and back. It loses precision in the process; some byes are converted to 0x00.

Also, it would be great to have support for ZeroMQ's Z85 encoding, in a similar way that I can choose subsets of Base64 encodings. As in: Base85 ( Ascii85 or Z85 ).

**Comment by ffraenz** [comment]
I've fixed a bug generating empty tuples and I've added the 'ZeroMQ' variant to Ascii85. Thank you for your feedback!

**Comment by bgever** [comment]
Thank you for the quick fix! It works perfect now, and also fantastic that ZeroMQ's Z85 has been added. 😄
