### ISSUE TITLE
Feature: Have an option to convert bytes to floats and doubles

### ISSUE THREAD

**Issue by 3d4m-vladimir** [cryptii/cryptii#124]
It is awesome that I can convert to Integers! 

Another awesome addition would be converting Bytes to Floats or Doubles.

<img width="1185" alt="Screenshot 2021-10-17 at 18 41 29" src="https://user-images.githubusercontent.com/50796908/137638704-1bb33350-421e-4f33-b4e5-b6f5bb7c58ec.png">

like here https://www.scadacore.com/tools/programming-calculators/online-hex-converter/

<img width="874" alt="Screenshot 2021-10-17 at 20 15 22" src="https://user-images.githubusercontent.com/50796908/137641630-92f354af-5fea-405f-b7ac-53e9c9cda3e2.png">

**Comment by ffraenz** [comment]
This won't make it into the cryptii project, as of now. However, over at ciphereditor, we already added IEEE 754 Single-precision and Double-precision floating-point formats to the [Number encoder operation](https://ciphereditor.com/explore/integer-float-format) with an option to choose between big-endian and little-endian. See https://github.com/cryptii/cryptii/issues/129 for more.
