### ISSUE TITLE
Pride month is long over

### ISSUE THREAD

**Issue by HamburgerPlsdotexe** [cryptii/cryptii#126]

**Comment by ffraenz** [comment]
I don't care.

**Comment by HamburgerPlsdotexe** [comment]
> I don't care.

That's pretty toxic, suit yourself.

**Comment by clawfire** [comment]
> > I don't care.
> 
> That's pretty toxic, suit yourself.

You are. xoxo

**Comment by HamburgerPlsdotexe** [comment]
> @HamburgerPlsdotexe It is your contribution that was toxic in the first place.
> 
> Let me explain:
> 
> 1. This is not a bug.
>    
>    * This issue is not about the functionality of the app or any of its features. It basically is (putting it very nicely) a content proposal.
>    * There is no definition of when 'pride' or 'pride month' takes place and there is no authority who could change that. In Luxembourg we celebrate pride in July. See [List of LGBT awareness periods](https://en.wikipedia.org/wiki/List_of_LGBT_awareness_periods).
>    * LGBT*s and LGBT* issues do not magically disappear outside of an awareness period. There is no 'wrong time' for celebrating pride and spreading awareness.
> 2. You are not using the bug report issue template. That's reason enough to close the issue without further attention.
> 3. You are wasting everyone's time as 'fixing this issue' would not introduce any substantial improvement. You are wasting my time as instead of preparing for my upcoming exam I need to deal with this.
> 4. About your comment: It is not up to you to tell anyone to suit themselves in this repository. And, to be frankly, I suited myself for way too long in the past. This pride flag is all about it and your issue confirms its necessity.
> 
> I did not leave the pride badge up on purpose. Changing it just wasn't on my priority list, lately. But now, I think I'll keep it around for a little longer. Cheers!

Sure, I was already content with "I don't care". You did not have to go out of your way to explain this. gl with your exams

**Comment by wibbuffey** [comment]
> "I was already content with 'I don't care'"
> proceeds to respond to that message

logical thinking

**Comment by HamburgerPlsdotexe** [comment]
> > "I was already content with 'I don't care'"
> > proceeds to respond to that message
> 
> logical thinking

I dont see an issue. if I want to be decent, I will.

**Comment by ffraenz** [comment]
I'll lock this thing. It's time to move on.
