### ISSUE TITLE
Feature: Android App Version

### ISSUE THREAD

**Issue by gulyasal** [cryptii/cryptii#134]
It would be terrific if this could be compiled into an Android app that I can copy/paste input/output to/from.  Is this possible?  Can I commission someone to make an .apk for me?

**Comment by ffraenz** [comment]
As of now we're not planning on releasing a native cryptii app for Android, iOS, Windows or macOS. However, cryptii is available on all of these devices in your browser of choice. For ciphereditor, we're planning to release desktop apps as well as to improve the PWA experience, see #129.
