### ISSUE TITLE
Feature: Add a launcher to the Source Code for people wanting an offline backup

### ISSUE THREAD

**Issue by George0079** [cryptii/cryptii#145]
I understand not wanting to condense the source code to EXE, APK, or some other application, but why isn't there an easy-to-use offline version?
I know that HTML files can pull from files directly on your computer, so it'll still be browser-based.

I may be asking for something that already exists, but if it does, then please push out an update to make it more intuitive.
I am not a coder. I have no interest in coding. I just want to encrypt my passwords manually, and your site is a wonderful resource. I would just prefer being able to access that resource without needing an internet connection.

**Comment by ffraenz** [comment]
Hi there! I've updated the local version and attached a build archive to [the latest release](https://github.com/cryptii/cryptii/releases/tag/v4.0.10) with an index.html file that can be opened in the browser offline. I hope this works for you.
