### ISSUE TITLE
Enigma S rotor II may use a wrong wiring (according to what's documented over the internet)

### ISSUE THREAD

**Issue by denismaggior8** [cryptii/cryptii#147]
**Steps to reproduce the bug**

1. Navigate to [cryptii.com](https://cryptii.com).
2. Use the following machine configurations

Machine type: Enigma S
Rotor 1: type I, position 1, ring 1 
Rotor 2: type II, position 1, ring 1 
Rotor 3: type III, position 1, ring 1 

3. Wipe the plugboard field
4. Include foreign chars
5. Encode the string "uadenis" (omitting the double quotes)

The output will be "gkkdooa", but I expected "gkkdjta". 

Looking at the code into Enigma.js, I found that Enigma S rotor II reports this wiring "UEMOATQLSHPKCYFWJZBGVXINDR" instead of the wiring documented over the internet which is "UEMOATQLSHPKCYFWJZBGVXIDNR".

It seams that the trailing 3 chars are different (Cryptii uses NDR instead of DNR).

Please have a look of https://www.cryptomuseum.com/crypto/enigma/wiring.htm#12

Could you please clarify?

Thanks.
Denis

**Comment by denismaggior8** [comment]
Anyone here?

**Comment by ffraenz** [comment]
Hi Denis, thank you for reporting this bug. I can confirm that `uemoatqlshpkcyfwjzbgvxidnr` is the correct wiring for wheel II of the Enigma S “Sondermaschine”. I'll prepare an update to fix this.

**Comment by denismaggior8** [comment]
Hi, thanks for the confirmation. To solve, please consider merging the PR
https://github.com/cryptii/cryptii/pull/148

Best regards

Denis Maggiorotto



P.za Angelo Mosso 1,

10023 Chieri (TO)

Mob:  +39 328 97 35 013

Mail:  ***@***.***

Web:  www.sunnyvale.it

**Comment by ffraenz** [comment]
Changes are now live on cryptii.com. Thank you!

**Comment by denismaggior8** [comment]
Thank you @ffraenz !
