### ISSUE TITLE
Feature: Support for plugins

### ISSUE THREAD

**Issue by vanBassum** [cryptii/cryptii#149]
Have you considered adding support for custom plugins? 

For example, I have a custom protocol we use at work. In this protocol, we use a rather weird framing scheme. It would be great if I could add a custom block, that shows our framing. 

One way I can see this happening is adding an option to the library that says : custom script. Here, people can upload their own JavaScript that does encode / decoding. 

Maybe this idea is a little wild, but it will allow users to add blocks that don't exist yet. Especially for 'company secret' algorithms etc. this would be great!

Oh, I just found this: https://github.com/xyflow/xyflow/discussions/3764 
Their Computing flows feature would be perfect for this. Of course, this is not a 'feature' anymore but a complete redesign.

**Comment by ffraenz** [comment]
Hi there! You're right, this would be a complete redesign and it's happening over at https://ciphereditor.com/. All operations in this project have been rewritten to use a common Extension API that will be opened up to third-party code, once declared stable. If you're interested in the development process, join the Discord server over at https://discord.gg/v5wNewjdxm.

**Comment by vanBassum** [comment]
Ah, thanks for the update, I just found this issue: https://github.com/cryptii/cryptii/issues/129 and played around with it a bit. Seems like it's heading in the direction I had in mind, very cool!
