### ISSUE TITLE
Wrong wiring for Enigma I "Norenigma" for rotor IV

### ISSUE THREAD

**Issue by IC3-512** [cryptii/cryptii#150]
The wiring of the Norenigma Rotor IV in the code does not match the expected wiring as specified on the
(https://www.cryptomuseum.com/crypto/enigma/i/)

File and Line Number:
cryptii/blob/main/src/Encoder/Enigma.js line 279

Current Wiring:
```
esovpzjayquirhxlnftgkdcmwb
```
Expected Wiring:
```
fgzjmvxepbwshqtliudykcnrao
```

The current wiring seems to be a copy-paste mistake. The sequence 'esovpzjayquirhxlnftgkdcmwb' corresponds to the standard wiring of Rotro IV

**Comment by ffraenz** [comment]
Hi @IC3-512! You're right, the current wiring in use for Norenigma wheel IV is not aligned with the expected one. Thank you for reporting this issue.

**Comment by ffraenz** [comment]
Changes are now live on cryptii.com. Thank you!
