### ISSUE TITLE
Hash function and HMAC are not selectable

### ISSUE THREAD

**Issue by kwon0408** [cryptii/cryptii#153]
**Steps to reproduce the bug**

1. Navigate to [cryptii.com](https://cryptii.com).
2. Change the type of the `Encode` block prepared by default to `Hash function` or `HMAC`

**Describe what you expected to happen**
The block should change into `Hash function` or `HMAC`, but it didn't and the block type modal just disappeared.

**Version, environment and state**

 * Firefox 131.0.3 on Windows 11 Version 23H2 (Build 22631.4317)
```json
{"version":"unknown","pipe":{"id":177272168,"url":"/","title":"Modular conversion, encoding and encryption online","description":"Web app offering modular conversion, encoding and encryption online. Translations are done in the browser without any server interaction. This is an Open Source project, code licensed MIT.","items":[{"name":"text"},{"name":"enigma","settings":{"model":"M3","reflector":"UKW-B","rotor1":"VI","position1":1,"ring1":1,"rotor2":"I","position2":17,"ring2":1,"rotor3":"III","position3":12,"ring3":1,"plugboard":"bq cr di ej kw mt os px uz gh","includeForeignChars":false}},{"name":"text"}],"content":{"data":"The quick brown fox jumps over the lazy dog."}}}
```

* Chrome 130.0.6723.70 on Windows 11 Version 23H2 (Build 22631.4317)
Alert popup cannot be copied in Chrome, but it was the default status.

**Comment by ffraenz** [comment]
Hi @kwon0408! Thank you for brining this to my attention. You are right, a bug blocked the use of encoders Hash function and HMAC. It's now fixed and the fix is available live. Does this work for you?

**Comment by kwon0408** [comment]
Now it works as expected, thanks!
