### ISSUE TITLE
Enigma M4 should have 4 rotor slots

### ISSUE THREAD

**Issue by albertyusuke** [cryptii/cryptii#20]
The M4 should have another slot to insert the "Greek" wheels, beta or gamma.
The reflectors for this is also different. (thin B and thin C)

**Comment by ffraenz** [comment]
Thank's for letting me know. Indeed, Enigma M4 introduces an additional rotor slot, two thin rotors beta & gamma and uses different reflectors. I've made a few code changes to the Enigma encoder to reflect these characteristics. Changes are live on [cryptii.com/enigma-machine](https://cryptii.com/enigma-machine). Does this work for you?
