### ISSUE TITLE
Cannot set the Ring Setting (Ringstellung)

### ISSUE THREAD

**Issue by albertyusuke** [cryptii/cryptii#21]
In your test for #20, there is a setting for Ringstellung: AAAV in the German Wikipedia, but I find that there is no way for me to set this on the UI.

Furthermore, the "Spruchschlüssel: VJNA" is equivalent to 22-10-14-1 Position. But in the test, it was initialized as 22-10-14-6. This discrepancy might be due to the effect of having a default Ring Setting.

**Comment by ffraenz** [comment]
In the [Enigma M4 test case](https://github.com/cryptii/cryptii/blob/6e4b7c0205cf3101f1098fa75f6d450fda0c919f/test/Encoder/Enigma.js#L88) for #20 I manually calculated the initial positions given the positions and the ring settings from the [Wikipedia article](https://de.wikipedia.org/w/index.php?title=Enigma-M4&oldid=176856055#Authentischer_Funkspruch). The test case and the Wikipedia settings produce the same underlying translation and thus the same result.

Nevertheless I added ring settings for each rotor to the UI to complete the Enigma simulation. You should now be able to reproduce the Wikipedia example inside the web app.

I am looking forward to your feedback!

**Comment by albertyusuke** [comment]
I was able to simulate and reproduce the Wikipedia example inside the web app.

Minor, but nothing I can't handle on my end, is the mapping of position numbers to letters. I'm not 100% sure, but it seems most examples for M4 uses the letter convention, while the older models uses the number convention.

Anyway thanks for quickly patching the problems for M4.

**Comment by albertyusuke** [comment]
I'm currently looking at this [message](https://enigma.hoerenberg.com/index.php?cat=The%20U534%20messages&page=P1030700) and it seems it only decodes the 1st 4 characters correctly before it becomes gibberish. I don't know what's wrong at the moment

**Comment by albertyusuke** [comment]
I think I know what the problem is, it seems when the ring setting was added, it also moved the notches with it. 
So in the example above, for Wheel positions: VMGC (22-13-7-3) and Rings: AACU (1-1-3-21), the first 4 characters decoded correct and the rotors should have moved VMGC->VMGG (22-13-7-7). But instead the 3rd rotor's position got rotated as well on after the 4th character, thus VMGC->VMHG (22-13-8-7). the rotor 4's G (7) position is now equivalent to the M (13) position where the notch is located because of the ring position U (21).

**Comment by ffraenz** [comment]
I have now a better understanding of how the ring settings work and fixed the implementation accordingly. I added your case to the tests. Looks good to me, does it work for you, too? Thank's again for your help!

**Comment by albertyusuke** [comment]
I checked a few manually, and it seems to look good too on my end.

**Comment by ffraenz** [comment]
Nice! Thank's! 🙌
