### ISSUE TITLE
Vigenere encoding

### ISSUE THREAD

**Issue by ypypy1** [cryptii/cryptii#22]
smt wrong with capitlal letter. they not encoded.

Anyone who reads Old and Middle English literary texts will be familiar with the mid-brown volumes of the EETS, with the 
Aoarrj dpx cebfv Ork jxo Mkghqk Ewqwitj pnzlzjbj ugaxx dquv bf ierosqjb wjvk ynl vso-ctras cwuexet rj zom EETS, anzo crp 

ABCDEFGHIJKL

**Comment by ffraenz** [comment]
You need to set 'case sensitivity' to 'no' inside the Vigenère cipher pane to get the desired outcome. On the following page this is preconfigured for you: https://cryptii.com/vigenere-cipher
