### ISSUE TITLE
Feature Request: wrap the position and ring dials on Enigma

### ISSUE THREAD

**Issue by pinduli** [cryptii/cryptii#26]
It would be nice to wrap the position and ring dials when using Enigma so that when they reach 26 we don't have to press minus 25 times or type in the field to change the amount to 1.

My use case has been testing the effect of moving the position one letter at a time on the decryption result.

**Comment by ffraenz** [comment]
Hi @pinduli! I just implemented rotation into the number setting. Position and ring settings now wrap as you described. Thank you for your feedback!

**Comment by pinduli** [comment]
Awesome, thanks!
