### ISSUE TITLE
HMAC-SHA1 

### ISSUE THREAD

**Issue by git3smurf** [cryptii/cryptii#27]
HMAC-SHA1 does not seem to be there anymore, only in the algorithms SHA-256 and SHA-516 seem to bee available… for some vintage application I need SHA1 though…  
Could this option  be made available again?

**Comment by ffraenz** [comment]
SHA-1 is currently not available in both Internet Explorer and Microsoft Edge, SHA-512 is not supported by Internet Explorer only. Please choose a different browser and the algorithms SHA-1 and SHA-512 will show up again in the HMAC & Hash function bricks.

**Comment by git3smurf** [comment]
Thanx for the quick respons… that was not easy to guess!
This generator [](https://www.liavaag.org/English/SHA-Generator/HMAC/)  fixed my problem in explorer though…
