### ISSUE TITLE
 tiny error in comment of ByteEncoder

### ISSUE THREAD

**Issue by LiuMengzhou** [cryptii/cryptii#33]
file: `ByteEncoder`
function: `bytesFromBase64String`
line: 243
```diff
- // byte 3: bits 1-2 from octet 3 joined by bits 1-6 from octet 4
+ // byte 3: bits 5-6 from octet 3 joined by bits 1-6 from octet 4
```
you can direct to the [location](https://github.com/cryptii/cryptii/blob/master/src/ByteEncoder.js#L243).

**Comment by LiuMengzhou** [comment]
BTW, [cryptii](https://cryptii.com/) is awesome!

**Comment by ffraenz** [comment]
Very true, I updated the comment you mentioned. Thank you!
