### ISSUE TITLE
"base64url" encoding

### ISSUE THREAD

**Issue by cbrunnkvist** [cryptii/cryptii#36]
It could be useful to include "base64url" It is essentially Base64 but with `/` and `+` replaced by `_` and `-`, 

Ref 1: https://tools.ietf.org/html/rfc4648#section-5
Ref 2: https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html#getUrlEncoder--

**Comment by ffraenz** [comment]
Hi @cbrunnkvist! Inside the Base64 brick settings `base64url` is listed as a variant. When you choose it you will get the output you describe.

**Comment by cbrunnkvist** [comment]
oh...wow! Variant!? I did not explore that dropdown 😆 

Removing this item from my "potential PR" list then 👍
