### ISSUE TITLE
Add more hash functions

### ISSUE THREAD

**Issue by CosmicToast** [cryptii/cryptii#38]
Of particular interest (to me) are:

- [CRC32](https://github.com/SheetJS/js-crc32)
- [MurmurHash3](https://github.com/garycourt/murmurhash-js)
- [Blake2b](https://github.com/dcposch/blakejs)

Linked are the proposed implementations.
The crc32 implementation claims to be standard within js.
The blake2 implementation is linked on the blake2 [website](https://blake2.net/).

**Comment by ffraenz** [comment]
Right now hash functions are limited to those offered through the Web Crypto API with the addition of `md5`. Adding more hash functions is definitely on the roadmap. First though, a mechanism needs to be put in place to lazily load external libraries and Web Assembly code only when needed by the current brick combination. The whole code separation challenge needs to be solved before we can tackle more algorithms that require external, well tested libraries.

**Comment by jeapostrophe** [comment]
I'd like to also request keccak256

**Comment by ffraenz** [comment]
Quick update: We won't be adding more hash functions to cryptii, as of now. However, over at [ciphereditor](https://ciphereditor.com/explore/cryptographic-hash-function), we already added CRC32 and Keccak to the hash operation and may add more hash functions in the future. See #129.

**Comment by jeapostrophe** [comment]
Thank you!
