### ISSUE TITLE
HMAC-SHA256 - Erroneous results

### ISSUE THREAD

**Issue by mtsiakiris** [cryptii/cryptii#40]
The procedure to calculate a HMAC-SHA256 (using flow: TEXT->HMAC/SHA-256->HASH) hash is invalid.

Test data
```
TEXT: 12345;78910
KEY: 12345
CORRECT HASH: 12476f110137a6c8243aa1ec839a4a09e7232ad682e407cc987ad3d1e2a91aef
```

**INVALID!: bff8836fb60ed93f10677334fb04315776e381f82b72c8ab9b6a0373d2fdbd69**

Check the screenshot.
![image](https://user-images.githubusercontent.com/10559137/54683639-d2d63f80-4b1a-11e9-8aa1-6c672c088dca.png)

**Comment by ffraenz** [comment]
Hi @mtsiakiris, the key setting is currently requested in hexadecimal format. Thus your key input `12345` is interpreted as hexadecimals instead of text. The result is correct. I understand that the UI may be misleading here, so I added the issue to the backlog. Thank's for reporting!
