### ISSUE TITLE
Shift of 26 generates an error

### ISSUE THREAD

**Issue by capybaras** [cryptii/cryptii#41]
<img width="368" alt="error" src="https://user-images.githubusercontent.com/5059270/55412215-06f72a80-5535-11e9-8f7f-4423e175b6b8.png">

**Comment by capybaras** [comment]
26 is effectively 0, but it shouldn't return an error

**Comment by ffraenz** [comment]
Thank you for reporting this issue. Until now the Affine cipher brick was the underlying engine for the Caesar cipher brick. Having the shift or b value set to 0 is not defined when using the Affine cipher.

I decoupled both ciphers. The Caesar cipher now accepts shift values like 0, 26, etc. Changes are rolling out over the next few hours: https://cryptii.com/pipes/caesar-cipher
