### ISSUE TITLE
Caesar cipher Dont do work as Expected while encoding :(

### ISSUE THREAD

**Issue by GhostyMan** [cryptii/cryptii#43]
The shift should have to work on Capital letters, Small letters and numeric values on each differently i.e. when I have to encode this string "DMkfWFbhj29cF3tdlD9pkuDnlOptF2VgmFJ0j19bGFV0HFR9" using Caesar cipher by 18 the expected outcome should be "VEcxOXtzb29uX3lvdV9hcmVfdGhlX2NyeXB0b19tYXN0ZXJ9".

have a look at (for more classification): https://www.xarg.org/2010/05/cracking-a-caesar-cipher/
https://www.xarg.org/tools/caesar-cipher/

**Comment by ffraenz** [comment]
Hi! There is no standard way of how the character case is treated in Caesar cipher. When dealing with Base64 content character case is crucial. However when dealing with a secret English message the character case could leak information about the plaintext. I added a new setting 'case strategy' to the Caesar cipher brick to let you choose between 3 strategies (Maintain case, Ignore case and Strict A ≠ a).

Changes are rolling out in the next few hours:
https://cryptii.com/pipes/caesar-cipher
