### ISSUE TITLE
Please add zbase32 encoding

### ISSUE THREAD

**Issue by axos88** [cryptii/cryptii#44]

**Comment by ffraenz** [comment]
Hi @axos88, a new brick called 'Base32' is now available including following variants:

- Base32 (RFC 3548, RFC 4648)
- Base32hex (RFC 4648)
- z-base-32
- Crockford's Base32
- Custom alphabet & padding

Changes are currently rolling out:
https://cryptii.com/pipes/base32

Cheers!

**Comment by axos88** [comment]
You rock :)
