### ISSUE TITLE
Hexadecimal to Base64 conversion is wrong

### ISSUE THREAD

**Issue by hezlog** [cryptii/cryptii#45]
Take the following example:
hexadecimal: ff ff ff ff ff ff

The correct base64 result is: ////////
The application returns: w7/Dv8O/w7/Dv8O/

**Comment by ffraenz** [comment]
Hello @hezlog, I can't reproduce the issue you describe. I get the expected result back. Which browser did you use? Can you attach a screenshot of the pipe you composed? Thank you!

**Comment by ffraenz** [comment]
Hello @hezlog, please make sure you use the current version of cryptii for the Base64 conversion over at https://cryptii.com/pipes/hex-to-base64.
