### ISSUE TITLE
Enigma machine display bug

### ISSUE THREAD

**Issue by pinduli** [cryptii/cryptii#47]
After the addition of letters next to the ring and positions settings (nice!), it seems, if you change the a position or ring using the keyboard and click out of the input box, the previous setting will be displayed even though the change took effect.

So if I input 3 into Position 2 when it has a 5 in it, and click out of the box, the encoded/decoded text will update properly, but Position 2 will still show 5. If I then click back in Position 2, it will show 3 until I click out again, after which it will show 5.

However, if I use the -/+ to change the setting aftword, the display will update properly.

**Comment by ffraenz** [comment]
Hello @pinduli! Thank you for filing this bug report. Indeed, the input and display value weren't properly kept in sync when typing values inside number settings. I updated the code accordingly. Changes are currently rolling out and should be available in a few hours. Would you check back if this resolves your issue? Thank you!

**Comment by pinduli** [comment]
I cleared my site cookie, and now it works as intended. Thanks!
