### ISSUE TITLE
Numeral system transform problem

### ISSUE THREAD

**Issue by ansenagy** [cryptii/cryptii#50]
Hi.

It looks like the numeral system transform has a precision problem big int numbers. For instance, the number "16305443177675634559" transformed from "decimal" to "decimal" gets "16305443177675635000". Binary, HEX and Octal transformations has the problem too. May be an internal register problem ?

![sample](https://user-images.githubusercontent.com/13204014/64141643-3f01e280-cddf-11e9-9ac9-8b06b572b293.png)

**Comment by ffraenz** [comment]
The numeral system encoder currently works with the native JavaScript Number type to calculate and is thus bound to its limits. It can't handle numbers such big. It shouldn't just let it happen, either. An error message is missing here. Thank you for reporting this issue!

**Comment by ffraenz** [comment]
I just pushed an update to the Numeral system encoder. In browsers that support [the new BigInt API](https://caniuse.com/#feat=bigint) arbitrarily large numbers are now processed in the numeral system brick. If it is not supported the brick will now show an error message to make sure it gets noticed. Changes are currently rolling out on [cryptii.com](https://cryptii.com). Thank you, again!

**Comment by ansenagy** [comment]
Great! It is an invaluable tool to have the transformation of large integers online Thank you very much for your effort.

Enviado desde Yahoo Mail para Android 
 
  El dom., 8 de sep. de 2019 a la(s) 11:17, Fränz Friederes<notifications@github.com> escribió:   
I just pushed an update to the Numeral system encoder. In browsers that support the new BigInt API arbitrarily large numbers are now processed in the numeral system brick. If it is not supported the brick will now show an error message to make sure it gets noticed. Changes are currently rolling out on cryptii.com. Thank you, again!
