### ISSUE TITLE
SHA-1 not available on Microsoft Edge (Chromium based)

### ISSUE THREAD

**Issue by zanechua** [cryptii/cryptii#55]
HMAC-SHA1 option doesn't seem to appear in the chromium based Edge that Microsoft is currently distributing. The browser is chromium based so it shouldn't have any issues like in #27.

I see that `edge` is defined in Hash.js as an exception so SHA1 will not appear and based on the code in Browser.js, it's a simple check based on the `detect` functionality in the `detect-browser` package. I think this might actually be an upstream issue?

Edge User Agent
```
According to useragent v2.2.1:

ua
rawUa: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362
string:
family: Edge
major: 18
minor: 18362
patch: 0
device: Other 0.0.0
```

```
According to ua-parser-js v0.7.20:

ua
ua: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362
browser
name: Edge
version: 18.18362
major: 18
engine
name: EdgeHTML
version: 18.18362
```

Edge Insider User Agent

```
According to useragent v2.2.1:
ua
rawUa: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3891.0 Safari/537.36 Edg/78.0.268.3
string:
family: Chrome
major: 78
minor: 0
patch: 3891
device: Other 0.0.0
```

```
According to ua-parser-js v0.7.20:

ua
ua: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3891.0 Safari/537.36 Edg/78.0.268.3
browser
name: Edge
version: 78.0.268.3
major: 78
engine
name: Blink
version: undefined
```

**Comment by ffraenz** [comment]
@zanechua Thank you for your detailed issue report! I've made some changes to correctly differentiate Microsoft Edge from the Chromium-based version of it. You may test the result [in the development environment](https://dev.cryptii.com/pipes/hmac). Does this work for you?

**Comment by zanechua** [comment]
Yes. The development environment does correctly display SHA-1 capability in the insider version of Edge now. :)

**Comment by ffraenz** [comment]
Changes are rolling out. Thank you!
