### ISSUE TITLE
[Spelling Alphabet] Add other languages

### ISSUE THREAD

**Issue by mnaoumov** [cryptii/cryptii#77]
https://en.wikipedia.org/wiki/Spelling_alphabet#Telephone_spelling_alphabets

**Comment by mnaoumov** [comment]
I found much more links

https://en.wikipedia.org/wiki/NATO_phonetic_alphabet
https://en.wikipedia.org/wiki/Spelling_alphabet
https://en.wikipedia.org/wiki/Finnish_Armed_Forces_radio_alphabet
https://en.wikipedia.org/wiki/Greek_spelling_alphabet
https://en.wikipedia.org/wiki/Japanese_radiotelephony_alphabet
https://en.wikipedia.org/wiki/Korean_spelling_alphabet
https://en.wikipedia.org/wiki/Russian_spelling_alphabet
https://en.wikipedia.org/wiki/Swedish_Armed_Forces_radio_alphabet
https://en.wikipedia.org/wiki/Dutch_orthography#Spelling_alphabet
https://en.wiktionary.org/wiki/Appendix:French_spelling_alphabet
https://en.wikipedia.org/wiki/Allied_military_phonetic_spelling_alphabets
https://en.wikipedia.org/wiki/APCO_radiotelephony_spelling_alphabet

https://de.wikipedia.org/wiki/Buchstabiertafel
https://ru.wikipedia.org/wiki/%D0%A4%D0%BE%D0%BD%D0%B5%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B0%D0%BB%D1%84%D0%B0%D0%B2%D0%B8%D1%82

https://en.wiktionary.org/wiki/Appendix:Italian_spelling_alphabet
https://en.wiktionary.org/wiki/Appendix:Finnish_spelling_alphabet
https://en.wiktionary.org/wiki/Appendix:German_spelling_alphabet
https://en.wiktionary.org/wiki/Appendix:Korean_spelling_alphabet
https://en.wiktionary.org/wiki/Appendix:Portuguese_spelling_alphabet
https://en.wiktionary.org/wiki/Appendix:Russian_spelling_alphabet
https://en.wiktionary.org/wiki/Appendix:Spanish_spelling_alphabet
https://en.wiktionary.org/wiki/Appendix:Swedish_spelling_alphabet

http://spellout.org/alphabets
https://spellingalphabets.com/
https://sites.google.com/view/meyersde/phonetic-alphabets
http://www.bckelk.ukfsn.org/phon.full.html

It will take a lot of time to process all of them carefully. In the meanwhile, I've added a big chuck of those

**Comment by ffraenz** [comment]
This won't make it into the cryptii project, as of now. However, we can bring your work into a new operation for [ciphereditor](https://ciphereditor.com). See #129 for more.
