### ISSUE TITLE
Feature request:   xor

### ISSUE THREAD

**Issue by bkdotcom** [cryptii/cryptii#8]
got something "encrypted" via xor...   need ability to input they key as binary/hex/string and xor with the input  (repeating the key as necessary)

**Comment by ffraenz** [comment]
I just implemented a brick called 'Bitwise Operation' supporting NOT, AND, OR, XOR, NAND, NOR and NXOR. Thank you for your feedback!

**Comment by q2dg** [comment]
To get the same result than, for instance, _printf "0x%X\n" $(( 0x76 ^ 0x89 ))_ I must select the "nxor" operator instead of the "xor" one. Is this an intended behaviour or is it a bug?
Thanks!
