### ISSUE TITLE
Feature: Add Baudot Code brick

### ISSUE THREAD

**Issue by ffraenz** [cryptii/cryptii#83]
> This is a historically very important code that links Morse Code to modern binary/numeric codes, it was used in telegraphy, and as I understand it, was used on the paper tape on the first computers such as Colossus, that were used in... cryptography.

Originally mentioned in https://github.com/cryptii/cryptii/issues/57#issuecomment-552918199

**Comment by ffraenz** [comment]
The Baudot-Murray-Code was already featured in [Cryptii v2](https://v2.cryptii.com/text/ita2) but was never transferred to v3. The paper tape itself is a special UI requirement which has not been implemented in v3. In addition I experienced a lack of documentation about paper tapes in general.

Implementing text-based encoding to binary-based values should be easy given the proper documentation.

**Comment by piersaitman** [comment]
Thanks for the link, that is really useful. I can see why it's a big deal to do it like that, as it's a special UI just for one mechanism, though it's fabulous. I can easily convert to 8-bit binary 'ascii-type' numbers in v3, I was just imagining the possibility of converting to 5-bit binary with Baudot encoding. Don't do it on my account though, as I can easily use v2.

**Comment by ffraenz** [comment]
@piersaitman Do you have a documentation about the complete Baudot character-number mappings at hand?

**Comment by piersaitman** [comment]
The character set varied with time and language, so if you did it, it would be worth picking one standard, e.g. ITA2, and mentioning in your panel at the bottom that different encoding methods existed. Several of the character maps are just on the wikipedia page here - https://en.wikipedia.org/wiki/Baudot_code#Original_Baudot_variants

You also have the annoyance of coding the shift characters, if you encode numbers etc.

**Comment by ffraenz** [comment]
Hi @piersaitman, I've implemented a Baudot code brick offering the variants listed on Wikipedia as well as a Punched tape viewer. As they are separate bricks they may be used in more scenarios (e.g. viewing Unicode characters on punched tapes with 8 rows).

You can test these changes in the development environment: https://dev.cryptii.com/pipes/AOUD5w. Please let me know if this works for you. I am looking forward to your feedback.

**Comment by piersaitman** [comment]
This is amazing. Does it default to the 5-bit view if the mechanism is Baudot? Also maybe you would do a little text in the bottom panel about it once the path is pipes/baudot or similar?

This is a fantastic resource, it's so easy to use and intuitive, and will help us out a lot, so thank you again. I will shout your praises from the rooftops, though I have limited influence in UK educational policy! If you want a review or something, just let me know.

I'd like to tell the children a little about you, and our correspondence, so if you'd like to write them a message to say hello, where you're from, why you made this website, why you like computing, what your favourite code is (?), that would be amazing, and hopefully inspiring for them, and you might get a message back - maybe in code ;-)

**Comment by ffraenz** [comment]
Thank you for your kind words, they made my day! I published the changes and created a preconfigured Baudot code landing page over at https://cryptii.com/pipes/baudot. I close this issue as it has been resolved but I'll definitely get back to you with a message to your students. Thank's again!

**Comment by piersaitman** [comment]
Hi Franz,

I think the punch tape display is wrong. The least significant bit should be at the top. The mini-punch marks are in the right place, the bits just need flipping.

Piers

**Comment by ffraenz** [comment]
@piersaitman I flipped the bit order on the punched tape, changes are rolling out. Thank's!

**Comment by piersaitman** [comment]
Hi Franz,

My pupils have decorated a little message for you to decrypt. We really appreciate your brilliant website, and this international spirit of cooperation is a thing of beauty in these rather dark times for the UK and Europe. If you would like to write anything to us about why and how you got into coding and cryptography, I think it would be really inspiring to share with the children.

Thanks,

Piers

![baudot-message](https://user-images.githubusercontent.com/56315221/70705808-a677da00-1ccc-11ea-93b8-a32cd3c8105e.jpg)

**Comment by piersaitman** [comment]
Also separately a minor bug, on https://cryptii.com/pipes/baudot (when the bytes are viewed by 5 bits), it seems like the program is adding on zeroes at the end to make it into multiples of 8 to be valid bytes.

**Comment by ffraenz** [comment]
Hi Piers,

this is such a nice artwork, thank you and your pupils! Here's my message to them. I won't use Baudot code for this one ;)

> To the youngest users of this project,
> 
> I am Fränz (pronounced like 'friends'), 25 years old. I grew up in Luxembourg and am now living in Berlin for the past 6 years. After studying Interaction Design and working as a web developer I have become a student again to get an even deeper understanding of computer science.
>
> As a child I always wanted to become an inventor. Years later I found myself doing exactly that digitally and I love it. Furthermore I am oddly fascinated about hidden data and messages. They are everywhere and play such an important role in today's society. That's why I think people should not be afraid of encoding and encryption methods. They rather should see them as simple building blocks that they can play with. This is essentially what I am aiming for with the Cryptii project, a playground making this invisible, abstract world tangible.
> 
> Thank you, too, for adding one more hidden message to the world, it's a lovely one! Your parents wouldn't understand it, would they? It is so cool to hear that you are dealing with this topic at such a young age. You are definetly on the right track to become the magicians of tomorrow, if you choose to. Keep going, stay open and curious!
> 
> Fränz

The trailing zeros are a known issue. Cryptii is not ready yet to deal with arbitrary bit-sized binary data. I will change that in the upcoming major version that I am working on.
