### ISSUE TITLE
Mistranslation bug

### ISSUE THREAD

**Issue by mollthecoder** [cryptii/cryptii#90]
If you include a super high shift on ceasar cypher , everything turns into a letter of the alphabet. I am not sure if this is a what, but I am assuming it is a bug.

![image](https://user-images.githubusercontent.com/63081316/79012658-cdd49b80-7b34-11ea-934f-d6d5ef49cf21.png)

**Comment by ffraenz** [comment]
Super high shift indeed, I did not expect the user to input number bigger than `2^53 - 1`. I'll change the implementation to use BigInt, if available. Also I don't like the scientific number formatting here. It's a low priority issue, though. Thank you for reporting this edge case!

**Comment by mollthecoder** [comment]
> Super high shift indeed, I did not expect the user to input number bigger than `2^53 - 1`. I'll change the implementation to use BigInt, if available. Also I don't like the scientific number formatting here. It's a low priority issue, though. Thank you for reporting this edge case!

Just a little developer tip, never assume anything. If for any reason you cannot make have a very large input, add some code if it is too high telling them it is too large and set it back to a reasonable number for them.

**Comment by ffraenz** [comment]
I added support for arbitrary large shift values to Caesar Cipher. Translations should now work as expected, even for large numbers. Changes are rolling out in the next few hours. If you still encounter problems, please reopen this issue. Thank's again for reporting!
