### ISSUE TITLE
Polybius Square Bug

### ISSUE THREAD

**Issue by tomkinsp** [cryptii/cryptii#91]
**Describe what you expected to happen**
The Polybius Square cipher has a limitation that it does not distinguish between "i" and "j". That is not the bug. The bug is the way in which the program handles this limitation.

During encryption for the Polybius Square, no ciphertext is output when the plaintext is "j".

I believe that a better solution to the "i/j" limitation of the cipher would be to output the same ciphertext for "j" as for "i" during encryption and that the ciphertext for "i/j" should be decrypted as "i" in all cases.

**Version, environment and state**

Inside the web app press `Ctrl+I`, copy the presented alert text and paste it into the block below.

```json
{"version":"4.0.7+master.baf6a85","env":{"name":"firefox","version":"75.0.0","os":"Windows 10"},"pipe":{"id":177272168,"url":"https://cryptii.com/","title":"Modular conversion, encoding and encryption online","description":"Web app offering modular conversion, encoding and encryption online. Translations are done in the browser without any server interaction. This is an Open Source project, code licensed MIT.","items":[{"name":"text"},{"name":"polybius-square","settings":{"alphabet":"abcdefghiklmnopqrstuvwxyz","rows":"12345","columns":"12345","separator":"","caseSensitivity":false,"includeForeignChars":false}},{"name":"text"}],"content":{"data":"The quick brown fox jumps over the lazy dog."}}}```

**Comment by ffraenz** [comment]
Thank you for reporting this issue. Indeed the i/j Polybius Square cipher limitation should be handled differently. I implemented changes such that for every alphabet containing "i" but not "j" both characters will now be treated equally when encoding. The decoding step stays the same. Changes are rolling out in the next few hours. If you still encounter problems, please reopen this issue.
